parameters:

services:
  app.age_calculator.age_calculator_service:
    class: App\AgeCalculator\AgeCalculatorService

  app.age_calculator.is_adult_service:
    class: App\AgeCalculator\IsAdultService

  app.age_calculator.age_calculator_manager:
    class: App\AgeCalculator\AgeCalculatorManager
    public: true
    arguments:
      - '@app.age_calculator.age_calculator_service'
      - '@app.age_calculator.is_adult_service'

  app.command.age_calculator_command:
    class: App\Command\AgeCalculatorCommand
    public: true
    arguments:
      - '@app.age_calculator.age_calculator_manager'
